SELECT A.AUTHOR_ID AS AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES*PRICE) AS TOTAL_SALES
FROM BOOK B
JOIN AUTHOR A
ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN BOOK_SALES S
ON S.BOOK_ID= B.BOOK_ID
WHERE SALES_DATE LIKE '2022-01%'
GROUP BY 1,3
ORDER BY 1 ASC, 3 DESC