SELECT ID, CASE 
            WHEN P.PERCENT <= 0.25 THEN "CRITICAL"
            WHEN P.PERCENT <= 0.5 THEN "HIGH"
            WHEN P.PERCENT <= 0.75 THEN "MEDIUM"
            ELSE "LOW" END AS COLONY_NAME
FROM 
    (SELECT ID, 
        PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS PERCENT
    FROM ECOLI_DATA) AS P
ORDER BY 1

                