SELECT YEAR, MONTH, GENDER, COUNT(*) AS USERS
FROM USER_INFO U
JOIN (SELECT USER_ID, YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH
      FROM ONLINE_SALE
     GROUP BY 1,2,3) AS O
ON O.USER_ID=U.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY 1,2,3
ORDER BY 1,2,3