-- 코드를 입력하세요
SELECT P.PRODUCT_ID AS PRODUCT_ID, PRODUCT_NAME, PRICE*AMOUNT AS TOTAL_SALES
FROM FOOD_PRODUCT P
JOIN (SELECT F.PRODUCT_ID AS PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
      FROM FOOD_ORDER F
      WHERE PRODUCE_DATE LIKE '2022-05%'
      GROUP BY 1
    ) AS O
ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY 1
ORDER BY 3 DESC, 1 ASC
