WITH COMBINED AS 
(SELECT SHIPMENT_ID, FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM ((SELECT *
        FROM FIRST_HALF)
    UNION
        (SELECT *
        FROM JULY)) AS U
GROUP BY FLAVOR
)
SELECT FLAVOR
FROM COMBINED
ORDER BY TOTAL_ORDER DESC
LIMIT 3