SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO AS I
JOIN 
    (SELECT TREE.ITEM_ID
    FROM ITEM_TREE AS TREE
    JOIN (SELECT INFO.ITEM_ID, INFO.ITEM_NAME, INFO.RARITY
        FROM ITEM_INFO AS INFO
        WHERE INFO.RARITY="RARE" ) AS R
    ON R.ITEM_ID= PARENT_ITEM_ID) AS C
ON C.ITEM_ID= I.ITEM_ID
ORDER BY 1 DESC