# 부모와 자식을 AND 연산 했을 때 부모 형질의 2진수와 같으면 부모 형질을 갖고 있는 것
SELECT A.ID, A.GENOTYPE, B.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA AS A
JOIN ECOLI_DATA AS B
ON A.PARENT_ID =B.ID
WHERE B.GENOTYPE & A.GENOTYPE = B.GENOTYPE
ORDER BY 1
