SELECT DISTINCT(ID), EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS AS D
JOIN (SELECT CODE
     FROM SKILLCODES
     WHERE NAME="Python" OR NAME="C#") AS S
ON D.SKILL_CODE & S.CODE = S.CODE
ORDER BY 1 ASC