SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, Y.MAX_VAL-E.SIZE_OF_COLONY AS YEAR_DEV, E.ID
FROM ECOLI_DATA AS E
JOIN 
    (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_VAL
        FROM ECOLI_DATA
        GROUP BY 1) AS Y
ON YEAR(DIFFERENTIATION_DATE) = Y.YEAR
ORDER BY 1 ASC, 2 ASC