WITH 
FRONT AS (
    SELECT SUM(CODE) AS CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
),
PYTHON AS (
    SELECT CODE FROM SKILLCODES WHERE NAME = 'Python'
),
CSHARP AS (
    SELECT CODE FROM SKILLCODES WHERE NAME = 'C#'
)

SELECT
    CASE
        WHEN (D.SKILL_CODE & F.CODE) > 0 AND (D.SKILL_CODE & P.CODE) > 0 THEN 'A'
        WHEN (D.SKILL_CODE & C.CODE) > 0 THEN 'B'
        WHEN (D.SKILL_CODE & F.CODE) > 0 THEN 'C'
    END AS GRADE,
    D.ID,
    D.EMAIL
FROM DEVELOPERS D
JOIN FRONT F ON 1 = 1
JOIN PYTHON P ON 1 = 1
JOIN CSHARP C ON 1 = 1
WHERE (D.SKILL_CODE & F.CODE) > 0 AND (D.SKILL_CODE & P.CODE) > 0 OR
    (D.SKILL_CODE & C.CODE) > 0 OR
    (D.SKILL_CODE & F.CODE) > 0
ORDER BY GRADE, ID;
